### ISSUE TITLE
Please add `XDG_DATA_DIRS` support

### ISSUE THREAD

**Issue by mgorny** [richardlehane/siegfried#242] opened 2024-02-23 17:01 UTC
If I'm not mistaken, currently Siegfried supports loading data from only one location — be it `SIEGFRIED_HOME`, `-home` or user's home directory. This is inconvenient for distribution packaging where we would like to install a system-wide copy of signature file for all users to be able to use.

Could you add support for iterating over `XDG_DATA_DIRS` (i.e. `/usr/share`) when the signature file isn't found in the home directory? I think this would combine the best of both worlds, i.e. users could still easily override the signature file by placing a new one in their home directory, and the system-installed signature file would be automatically used otherwise.

**Comment by ross-spencer** [comment] 2024-02-23 19:21
Have you evaluated the work associated with this issue @mgorny? https://github.com/richardlehane/siegfried/issues/216

**Comment by mgorny** [comment] 2024-02-23 19:28
I'm sorry but I don't understand the question.

**Comment by ross-spencer** [comment] 2024-02-23 19:29
@mgorny that issue is titled: "use the xdg base directory specification for home directory" <-- seems like it's a duplicate of this, or that something in its implementation isn't working for you?

**Comment by mgorny** [comment] 2024-02-23 19:47
Unless I'm mistaken, #216 only implemented `XDG_DATA_HOME` (e.g. `~/.local/share`), while I am talking of `XDG_DATA_DIRS` (e.g. `/usr/local/share:/usr/share`).

Basically, the program should *write* new files to `XDG_DATA_HOME`. However, when reading, it should search `XDG_DATA_HOME`, followed by colon-separated list of `XDG_DATA_DIRS`, until it finds the expected file.

From https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html:

> `$XDG_DATA_HOME` defines the base directory relative to which user-specific data files should be stored. […]
>
> `$XDG_DATA_DIRS` defines the preference-ordered set of base directories to search for data files in addition to the `$XDG_DATA_HOME` base directory. The directories in `$XDG_DATA_DIRS` should be seperated with a colon ':'.

**Comment by richardlehane** [comment] 2024-06-22 00:30
Hi Michał, I've added functionality to search XDG_DATA_DIRS when choosing the home directory. This will be available in the next release, due in about a week. If you have a chance to test it I'd appreciate, there's a release candidate available here: https://github.com/richardlehane/siegfried/releases/tag/v1.11.1-rc4

**Comment by mgorny** [comment] 2024-06-22 09:24
Thanks. At a first glance, it seems to work fine!

**Closed** 2024-06-28 00:32 UTC
